// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPSzDmXGmJ2lAJWYJvD0bpQytStWbuoXY',
    appId: '1:906326345309:web:619c243da05cd464ba2fb4',
    messagingSenderId: '906326345309',
    projectId: 'crypto-trade-sim-8c120',
    authDomain: 'crypto-trade-sim-8c120.firebaseapp.com',
    storageBucket: 'crypto-trade-sim-8c120.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdqPYegibeNMAi_0Yo-Rq7HUfIaZscNnA',
    appId: '1:906326345309:android:98efb2bd00380405ba2fb4',
    messagingSenderId: '906326345309',
    projectId: 'crypto-trade-sim-8c120',
    storageBucket: 'crypto-trade-sim-8c120.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQor6s-uZwjLj2eFOWE8IuEZqW9GQbN5A',
    appId: '1:906326345309:ios:8fca97178cf11e44ba2fb4',
    messagingSenderId: '906326345309',
    projectId: 'crypto-trade-sim-8c120',
    storageBucket: 'crypto-trade-sim-8c120.firebasestorage.app',
    iosBundleId: 'com.example.tradDer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQor6s-uZwjLj2eFOWE8IuEZqW9GQbN5A',
    appId: '1:906326345309:ios:8fca97178cf11e44ba2fb4',
    messagingSenderId: '906326345309',
    projectId: 'crypto-trade-sim-8c120',
    storageBucket: 'crypto-trade-sim-8c120.firebasestorage.app',
    iosBundleId: 'com.example.tradDer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPSzDmXGmJ2lAJWYJvD0bpQytStWbuoXY',
    appId: '1:906326345309:web:9de21cbe96e92683ba2fb4',
    messagingSenderId: '906326345309',
    projectId: 'crypto-trade-sim-8c120',
    authDomain: 'crypto-trade-sim-8c120.firebaseapp.com',
    storageBucket: 'crypto-trade-sim-8c120.firebasestorage.app',
  );
}
